### ISSUE TITLE
Multiline evaluation issue and `e_v` missing

### ISSUE THREAD

**Issue by luraess** [pohlan/SimpleSheet.jl#2]
https://github.com/pohlan/SimpleSheet.jl/blob/61570b08a7a3486a4e12b367589846352d674f31/run_it_diffeq_expl.jl#L106

Note that
- as @pohlan reported, multiline statement are only evaluated if operator is at the end of previous line
- `e_v` is missing in this version (i.e. implicitly set to 1) which makes the physics to run much faster (factor 1e3)

**Comment by mauro3** [comment]
> as @pohlan reported, multiline statement are only evaluated if operator is at the end of previous line

Yes, that one is annoying as no error gets thrown.  In my defense, I copied that error from you, @luraess ;-)

**Comment by mauro3** [comment]
I'll push a fix in a sec

**Comment by luraess** [comment]
I should have fixed the multiline issue in my owl-life. `e_v` showing up "explicitly" may be desired...
